name: html to pdf
  uses: misaelnieto/web_to_pdf_action@master
  with:
    webPageURL: http://romulogcerqueira.github.io/online-cv
    outputFile: cv_en.pdf
    usePuppeteer: true
    useScreen: true
    pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
