name: HTML to PDF Conversion

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Convert HTML to PDF
        run: node convert.js

      - name: Archive PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted-pdf
          path: cv_en.pdf
