name: 'HTML2PDF'
description: 'Convert an HTML file to a PDF document'
inputs:
  html:
    description: 'html file to convert'
    required: true
outputs:
  pdf:
    description: 'output file'
runs:
  using: 'docker'
  image: 'docker://connormckelvey/html2pdf:v0.0.3'
  args:
    - -html 
    - ${{ index.html }}
    - -output 
    - ${{ index.html }}.pdf
