name: create PDF file
on: 
  push:
    branches: 
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: convert page to pdf
      uses: wei/curl@master
      with:
        args: https\://v2.convertapi.com/convert/web/to/pdf\?download\=attachment\&secret\=${{ secrets.CONVERTAPI }}\&url\=https%3A%2F%2Fhttps://romulogcerqueira.github.io/online-cv/ -o cv_en.pdf
    - name: commit PDF to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: generate PDF from gh-pages
        branch: gh-pages
        file_pattern: cv_en.pdf
